# Use a specific Python base image
FROM python:3.10.5-slim-buster

# Disable Python bytecode generation
ENV PYTHONDONTWRITEBYTECODE=1

# Set working directory inside the container
WORKDIR /app

# Set environment variables for Flask
ENV FLASK_APP=vgg_service.py
ENV FLASK_RUN_HOST=0.0.0.0

# Install dependencies from requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip \
    --mount=type=bind,source=requirements.txt,target=requirements.txt \
    python -m pip install -r requirements.txt

# Copy the application code into the container
COPY . .

# Expose the port used by the Flask app (ensure this matches your app's port)
EXPOSE 8000

# Command to run the Flask app
CMD ["python", "vgg_service.py"]
